set(_CATKIN_CURRENT_PACKAGE "ssoni_gui")
set(ssoni_gui_VERSION "0.1.0")
set(ssoni_gui_MAINTAINER "WonJunhee <roscore@kakao.com>")
set(ssoni_gui_PACKAGE_FORMAT "1")
set(ssoni_gui_BUILD_DEPENDS "qt_build" "roscpp" "robotis_math" "ssoni_arm_module_msgs" "robotis_controller_msgs" "ssoni_perception_msgs" "sensor_msgs/RegionOfInterest" "libqt4-dev")
set(ssoni_gui_BUILD_EXPORT_DEPENDS "qt_build" "roscpp" "libqt4-dev")
set(ssoni_gui_BUILDTOOL_DEPENDS "catkin")
set(ssoni_gui_BUILDTOOL_EXPORT_DEPENDS )
set(ssoni_gui_EXEC_DEPENDS "qt_build" "roscpp" "libqt4-dev")
set(ssoni_gui_RUN_DEPENDS "qt_build" "roscpp" "libqt4-dev")
set(ssoni_gui_TEST_DEPENDS )
set(ssoni_gui_DOC_DEPENDS )
set(ssoni_gui_URL_WEBSITE "")
set(ssoni_gui_URL_BUGTRACKER "")
set(ssoni_gui_URL_REPOSITORY "")
set(ssoni_gui_DEPRECATED "")